### ISSUE TITLE
FFI SSI create and push the did doc to registry mgmt

### ISSUE THREAD

**Issue by sKudryashov** [knox-networks/ssi#109]

**Comment by fkim7** [comment]
Please see #106 and also if we can have a separate ssi dylib

**Comment by sKudryashov** [comment]
When used with https, returns status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }

**Comment by sKudryashov** [comment]
When launched against locally built registry management- it works, both in FFI and in test: test_create_did_integration, when launched against https://reg.sandbox5.knoxnetworks.io:443 from local dev machine and from CI, the same `Unknown, message: "transport error"` occurs

**Comment by sKudryashov** [comment]
Option 2 is chosen, standard logging is enabled for FFI in monetae, the same approach will be implemented in SSI.
