### ISSUE TITLE
Add & Integrate Test Vectors For Data Integrity Proofs

### ISSUE THREAD

**Issue by LuisOsta** [knox-networks/ssi#163]

**Comment by LuisOsta** [comment]
See test vectors mentioned in https://github.com/w3c/vc-data-integrity/issues/221

**Comment by LuisOsta** [comment]
Important links - https://github.com/w3c/vc-test-suite-implementations/tree/main#vc-test-suite-implementations and https://github.com/w3c/vc-di-eddsa-test-suite/tree/main

**Comment by fkim7** [comment]
can be tested thru SSI CLI , or GHA which runs
`
          ssi_cli test-ed25519-signature2020 --input-file TestVectors/unsigned.json --key-pair-file TestVectors/keyPair.json --comparison-file TestVectors/Ed25519Signature2020/signedEdSig.json
`
https://github.com/knox-networks/ssi/blob/761d167664b30603b4e49905c540b0a80a79bffc/.github/workflows/vc_model_spec_test.yaml
https://github.com/knox-networks/ssi/blob/761d167664b30603b4e49905c540b0a80a79bffc/.github/workflows/data_integrity_spec_test.yaml

https://github.com/knox-networks/ssi/blob/761d167664b30603b4e49905c540b0a80a79bffc/core/src/proof.rs#L118
