### ISSUE TITLE
Integrate VC Data Model Spec Test Suite Into SSI

### ISSUE THREAD

**Issue by LuisOsta** [knox-networks/ssi#166]
Should incorporate into GHA for automated testing, along with DIDs

**Comment by LuisOsta** [comment]
Link to our fork - https://github.com/knox-networks/vc-test-suite

**Comment by LuisOsta** [comment]
I've filed https://github.com/w3c/vc-test-suite/issues/135 to deal with the proof-related issues we were having due to us expecting certain properties to be part of any proof object

**Comment by LuisOsta** [comment]
When you exclude the features, we don't support yet we've got 6 failures currently I've attached the report below/Users/luisosta/vc-test-suite/implementations/index.html

**Comment by LuisOsta** [comment]
One spec test remains failing and its the one that requires the verifiableCredential field to be optional, which to me is weird in concept but there's more information here - https://github.com/w3c/vc-test-suite/pull/113. Should we file an issue with the VC spec to clarify the language

**Comment by LuisOsta** [comment]
Here's an updated report /Users/luisosta/vc-test-suite/implementations/KnoxNetworks-report.json

**Comment by LuisOsta** [comment]
I've fixed the last issue, the `verifiableCredential` issue is completely correct. Here's a link to the 1.1 spec - https://www.w3.org/TR/vc-data-model/#presentations-0. What remains is the proof-related issues - https://github.com/w3c/vc-test-suite/issues/135

**Comment by LuisOsta** [comment]
Our repo - https://github.com/knox-networks/vc-test-suite has updated the examples to not be malformed and added the Knox Networks report

**Comment by fkim7** [comment]
Thanks- updated results can be found here https://knox-networks.github.io/vc-test-suite/implementations/

some comments
2.3 Credential Status - why do we show no support? 
Credential Schema- I think we should be able to address this in the upcoming sprints as we add VC schema
ZKP- Would be interesting to see how the other providers with support passed the tests.

**Comment by fkim7** [comment]
results here https://knox-networks.github.io/vc-test-suite/implementations/
