### ISSUE TITLE
Add Support For URDNA2015 or RDFC1.0 (or Latest standard) Normalization In Creating Data Integrity Proofs

### ISSUE THREAD

**Issue by LuisOsta** [knox-networks/ssi#29]
Right now the `normalize` function in the `normalization` module doesn't really do anything

**Comment by LuisOsta** [comment]
We need to:

1. Create RDF Data Structures (`DataSet`, `Triples`, etc.)
2. Implement the URDNA2015 Normalization algorithm using the RDF Data Structures
3. Implement functionality to convert a JSON-LD document to a RDF `DataSet`
4. Implement functionality to convert a RDF `DataSet` to `n-quads` (string version)

**Comment by fkim7** [comment]
I'm fine w holding off 3 &4 until we get the support we need from Rust in terms of 3PP libraries (JSON GOLD equivalent), GAT support, etc.  As the goal is to be able to enable querying for customer identity data, I'm ok to present the bankcard VC that will be urdna normalized by the golang credential adapter.  CW can expose an API returns this data or rather a subset of data (Address removed etc if possible) for demo purposes.

**Comment by LuisOsta** [comment]
The main libraries in question are:

- jsonld: https://github.com/timothee-haudebourg/json-ld
- RDF:  https://github.com/pchampin/sophia_rs

**Comment by fkim7** [comment]
can be tested thru SSI CLI , or GHA which runs
`
          ssi_cli test-ed25519-signature2020 --input-file TestVectors/unsigned.json --key-pair-file TestVectors/keyPair.json --comparison-file TestVectors/Ed25519Signature2020/signedEdSig.json
`
https://github.com/knox-networks/ssi/blob/761d167664b30603b4e49905c540b0a80a79bffc/.github/workflows/vc_model_spec_test.yaml
https://github.com/knox-networks/ssi/blob/761d167664b30603b4e49905c540b0a80a79bffc/.github/workflows/data_integrity_spec_test.yaml

https://github.com/knox-networks/ssi/blob/761d167664b30603b4e49905c540b0a80a79bffc/core/src/proof.rs#L118
