### ISSUE TITLE
Implement "Create Verifiable Presentation"

### ISSUE THREAD

**Issue by sKudryashov** [knox-networks/ssi#30]
Implement Verifiable Credential according to this specification
https://www.notion.so/Create-Integrate-Core-SSI-Rust-Library-Design-9eb9e58093a04a7d84bb476ac0324a7d#7febe5cc49c94f5180527fbdc028db57

**Comment by Ryanmtate** [comment]
https://github.com/knox-networks/ssi/pull/37

**Comment by Ryanmtate** [comment]
Remaining questions around test practices
