### ISSUE TITLE
Implement `From<serde_json::Value>` Trait For VerifiableCredentials and Credential Struct

### ISSUE THREAD

**Issue by LuisOsta** [knox-networks/ssi#36]

**Comment by LuisOsta** [comment]
In order for our library to be generally useful. And for it to work with storage (to convert from a stored format to in memory). We need to be able to convert to `serde_json::Value` and back. This is made more complex due to the requirement to support optional properties.


Right now we support converting from our structs to `serde_json::Value`. But we do not support going from `serde_json::Value` to the structs.

**Comment by sKudryashov** [comment]
Custom deserialization exlored, tried, and also explored custom deserealization/serialization by field. It is taken as an approach, the advantage is that you customize serialization/deserialization only for certain fields, the rest is being deserialized as usual.
