### ISSUE TITLE
Investigate traits usage in SSI library, whether to move them in corresponding crates or keep in the core library

### ISSUE THREAD

**Issue by sKudryashov** [knox-networks/ssi#42]
To prevent circurar dependencies between SSI crates and SSI core library we need to investigate traits usage in SSI library, whether to move them in corresponding crates or keep in the core library.

**Comment by fkim7** [comment]
@sKudryashov please confirm if still required and close as necessary.

**Comment by sKudryashov** [comment]
Not required for now
