### ISSUE TITLE
Evaluate Moving Away From `Chrono` To `hifitime` 

### ISSUE THREAD

**Issue by LuisOsta** [knox-networks/ssi#71]
Due to a recent change Chrono now depends on https://github.com/strawlab/iana-time-zone which has a C++ dependency in order to support Haiku OS (https://github.com/strawlab/iana-time-zone/tree/main/haiku). This is not feature gated code which means that it would lead to `ssi` and all consumers also being dependent on C++ code

**Comment by LuisOsta** [comment]
Also we should consider whether it would be possible to just have our own implementation of creating a timestamp that is formatted in the rfc_3339 spec as we use it only in specific areas (at least for now)

**Comment by LuisOsta** [comment]
@mkatychev What do you think about the comment the maintainer of `iana-time-zone` made in https://github.com/strawlab/iana-time-zone/issues/89? Does that remove your concerns about the C++ dependency in our Cargo.lock or do you think we should just move to `hifitime`?

**Comment by mkatychev** [comment]
I see so the git index is maintained but not build. That's fine. We can close this ticket
